<!--
SPDX-FileCopyrightText: 2026 Froststrap

SPDX-License-Identifier: MPL-2.0
-->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <InfAppVersion Condition="'$(AppVersion)' == ''">preversion</InfAppVersion>
    <AppVersion Condition="'$(AppVersion)' == ''">0.0.0</AppVersion>
    <OutputType Condition="!$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
    <OutputType Condition="$([MSBuild]::IsOSPlatform('Windows'))">WinExe</OutputType>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>$(AppVersion)</Version>
    <FileVersion>$(AppVersion)</FileVersion>
    <InformationalVersion>$(InfAppVersion)</InformationalVersion>
    <Company>Froststrap</Company>
    <Product>$(AssemblyName)</Product>
    <AssemblyName>Froststrap</AssemblyName>
    <RootNamespace>Froststrap</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  	<PublishReadyToRun>true</PublishReadyToRun>
  	<!-- <PublishTrimmed>true</PublishTrimmed> -->
  	<NeutralLanguage>en</NeutralLanguage>
    <Description>Froststrap - A Fishstrap fork</Description>
    <ApplicationIcon>Froststrap.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);CA1416;CA2007;CA1863;CA1031;CA1019;CA2000;CA1852;CA2216;CA1812;CA5392;SYSLIB1045;SYSLIB1054;CA5351</NoWarn>
    <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
    <DefineConstants Condition="$([MSBuild]::IsOSPlatform('MacOS'))">$(DefineConstants);__APPLE__</DefineConstants>
  </PropertyGroup>

  <!-- Resources needed by Avalonia -->
  <ItemGroup>
    <AvaloniaResource Include="Resources/**" />
    <AvaloniaResource Include="UI/AppThemes/EditorThemes/*.xshd" />
    <AvaloniaResource Include="Froststrap.ico" />
    <AvaloniaResource Include="Froststrap.png" />
    <AvaloniaResource Include="FroststrapTray.ico" />
    <AvaloniaResource Include="UI\Elements\Base\BackgroundPanel.axaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Froststrap.ico" />
    <EmbeddedResource Include="Froststrap.png" />
    <EmbeddedResource Include="FroststrapTray.ico" />
    <EmbeddedResource Include="Resources\**\*.*" Exclude="Resources\**\*.resx" />
    <EmbeddedResource Include="NLog.config">
      <LogicalName>NLog.config</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <!-- NuGet packages -->
  <ItemGroup>
    <PackageReference Include="AnimatedImage.Avalonia" Version="2.1.4" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Wayland" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="ktsu.CredentialCache" Version="1.3.40" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="NLog" Version="6.2.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="PuppeteerSharp" Version="24.42.0" />
    <PackageReference Include="PuppeteerExtraSharp" Version="3.1.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.8" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.321" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../libs/ColorPicker/ColorPicker.AvaloniaUI/ColorPicker.AvaloniaUI.csproj" />
    <ProjectReference Include="../libs/LucideAvalonia/LucideAvalonia/LucideAvalonia.csproj" />
    <ProjectReference Include="../libs/FluentAvalonia/src/FluentAvalonia/FluentAvalonia.csproj" />
    <ProjectReference Include="../backend/backend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="Froststrap.Models.Attributes.BuildMetadataAttribute">
      <_Parameter1>$([System.DateTime]::UtcNow.ToString("s"))Z</_Parameter1>
      <_Parameter2>$(COMPUTERNAME)/$(USERNAME)</_Parameter2>
      <_Parameter3>$(CommitHash)</_Parameter3>
      <_Parameter4>$(CommitRef)</_Parameter4>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources/Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources/Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <Target Name="CopyVirtualDisplayFromBackend"
          AfterTargets="Build"
          Condition="$([MSBuild]::IsOSPlatform('OSX'))">

    <PropertyGroup>
      <BackendOutDir>$(MSBuildProjectDirectory)/../backend/bin/$(Configuration)/$(TargetFramework)/</BackendOutDir>
    </PropertyGroup>

    <Copy SourceFiles="$(BackendOutDir)libvirtualdisplay.dylib"
          DestinationFolder="$(OutDir)"
          SkipUnchangedFiles="true"
          Condition="Exists('$(BackendOutDir)libvirtualdisplay.dylib')" />
  </Target>
</Project>
