# SPDX-FileCopyrightText: 2026 Froststrap
#
# SPDX-License-Identifier: MPL-2.0

[workspace]
resolver = "3"
members = [
  "backend",
  "notify",
  "virtualdisplay",
]
default-members = [
  "backend",
  "virtualdisplay"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = [
  "Invra <identificationsucks@gmail.com>",
  "UltimatePlayer97 <gogole.help134@gmail.com>",
  "RealMeddsam <meddsamreal@gmail.com>"
]

[workspace.dependencies]
libc = "0.2"
objc2 = "0.6"
block2 = "0.6"
objc2-foundation = "0.3"
objc2-user-notifications = "0.3"

[workspace.dependencies.rustbus]
version = "0.19.3"
default-features = false

[workspace.dependencies.notify]
path = "notify"

[workspace.dependencies.windows]
version = "0.62.2"
features = [
  "UI_Notifications",
  "Data_Xml_Dom",
]
