#!/bin/bash
USER=${SUDO_USER:-$USER}
USER_HOME=$(getent passwd "$USER" | cut -d: -f6)

APP_NAME="Froststrap"
BINARY_PATH="/usr/bin/Froststrap"
ICON_PATH="/usr/share/icons/hicolor/512x512/apps/froststrap.png"
DESKTOP_DIR="$USER_HOME/.local/share/applications"

mkdir -p "$DESKTOP_DIR"

cat <<EOF > "$DESKTOP_DIR/$APP_NAME.desktop"
[Desktop Entry]
Version=2.0.0
Type=Application
Name=Froststrap
Comment=A fork of Fishstrap, focused on performance and customization
Exec=$BINARY_PATH %u
Icon=$ICON_PATH
Terminal=false
Categories=Game;
MimeType=x-scheme-handler/roblox;x-scheme-handler/roblox-player;
EOF

chown "$USER:$USER" "$DESKTOP_DIR/$APP_NAME.desktop"
chmod 644 "$DESKTOP_DIR/$APP_NAME.desktop"
