services:
  deeplx:
    image: ghcr.io/owo-network/deeplx:latest
    container_name: deeplx
    restart: unless-stopped
    ports:
      - "1188:1188"
    environment:
      - DEEPLX_CACHE=true
      - DEEPLX_CACHE_EXPIRE=604800
    volumes:
      - ./deeplx_cache:/app/cache